name: buildFrontendPipeline

on:
  workflow_call:
    inputs:
      do_require:
        description: 'Directory to the folder in which the app is located.'
        required: true
        type: string
jobs:
  checkout:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        if: ${{ inputs.do_require }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      