name: Helm chart Pipeline

on:
  workflow_call:
    inputs:
      chart-directory:
        required: true
        type: string
        default: ${{ github.event.repository.name }}

      version:
        required: true
        type: string
        default: 'undefined' 

jobs:
  Helm:
    name: helm
    runs-on: ubuntu-22.04

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with: 
            fetch-depth: 0

        - name: Package Helm Chart
          run: helm package helm/${{ inputs.chart-directory }} --destination helm-chart

        - name: Upload Artifact 
          uses: actions/upload-artifact@v3
          with:
                name: ${{ inputs.chart-directory }}-chart-${{inputs.version }}
                path: helm-chart
